//! Domain validation limits shared by Core modules.

pub const MAX_PROJECT_NAME_CHARS: usize = 128;
pub const MAX_BRIEF_SUMMARY_CHARS: usize = 4_000;
pub const MIN_GENERATION_DURATION_SECONDS: u32 = 1;
pub const MAX_GENERATION_DURATION_SECONDS: u32 = 900;
pub const MAX_PROVIDER_TOOL_NAME_CHARS: usize = 64;
pub const MAX_COMPACTION_SUMMARY_FIELD_CHARS: usize = 16_000;
pub const MAX_COMPACTION_SUMMARY_ITEMS: usize = 256;
pub const CONTEXT_ESTIMATED_BYTES_PER_TOKEN: u64 = 3;
pub const CONTEXT_SOFT_PRESSURE_PERCENT: u64 = 75;
pub const CONTEXT_HARD_PRESSURE_PERCENT: u64 = 90;
pub const CONTEXT_TOOL_RESULT_SPILL_THRESHOLD_BYTES: usize = 16 * 1_024;
pub const CONTEXT_TOOL_RESULT_PREVIEW_CHARS: usize = 512;
pub const CONTEXT_COMPACTION_MIN_RECENT_TURNS: usize = 2;
pub const CONTEXT_COMPACTION_SUMMARY_OBJECTIVE_CHARS: usize = 4_096;
pub const CONTEXT_COMPACTION_SUMMARY_ITEM_CHARS: usize = 512;
pub const CONTEXT_COMPACTION_SUMMARY_MAX_ITEMS: usize = 24;
pub const CONTEXT_COMPACTION_UNKNOWN_TARGET_PERCENT: u64 = 70;
pub const MIN_GENERATION_CANDIDATES: u8 = 1;
pub const MAX_GENERATION_CANDIDATES: u8 = 4;
pub const CONTINUITY_BINDING_FORMAT_REVISION: &str = "autostudio.continuity-binding/1";
pub const COMPACTION_FORMAT_REVISION: &str = "autostudio.compaction/1";
pub const CONTEXT_SURFACE_LEGACY_FORMAT_REVISION: &str = "autostudio.context-surface/1";
pub const CONTEXT_SURFACE_FORMAT_REVISION: &str = "autostudio.context-surface/2";
